"""Add pagination and reconciliation indexes

Revision ID: 06934b407916
Revises: d9aafb8c682f
Create Date: 2026-06-18 17:09:23.143133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06934b407916'
down_revision = 'd9aafb8c682f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_account_created_desc', ['account_id', sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_txn_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_status_created')

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_account_created_desc')

    # ### end Alembic commands ###
