"""add provider fields to transaction

Revision ID: 52e29b6a167b
Revises: 06934b407916
Create Date: 2026-06-18 18:26:09.712727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e29b6a167b'
down_revision = '06934b407916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_provider_reference'), ['provider_reference'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_provider_reference'))
        batch_op.drop_column('provider')
        batch_op.drop_column('provider_reference')

    # ### end Alembic commands ###
