"""Add composite indexes for common query patterns

Revision ID: d75331e1f6e9
Revises: 52e29b6a167b
Create Date: 2026-06-19 09:34:52.081337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75331e1f6e9'
down_revision = '52e29b6a167b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_balance_snapshot_account_id_desc', ['account_id', sa.literal_column('id DESC')], unique=False)

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_account_transaction', ['account_id', 'transaction_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_txn_type_status_ref_created', ['type', 'status', 'provider_reference', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_type_status_ref_created')

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_account_transaction')

    with op.batch_alter_table('balance_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_balance_snapshot_account_id_desc')

    # ### end Alembic commands ###
