"""Add composite index on ledger_entries(account_id, status, id)

Revision ID: d9aafb8c682f
Revises: 52ea82edaa80
Create Date: 2026-06-18 16:51:55.953586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9aafb8c682f'
down_revision = '52ea82edaa80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_account_status_id', ['account_id', 'status', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_account_status_id')

    # ### end Alembic commands ###
